name: Release
on:
  release:
    types: [created]
jobs:

  prepare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: generate lock files
        run: yarn
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: yarn
      - name: generate tests datas
        run: |
          yarn list > yarn.list
      - uses: actions/upload-artifact@v2
        with:
          name: prepare
          path: |
            ./yarn.list
            ./yarn.lock

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ prepare ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: prepare
          path: .
      # try to perform a nodejs setup
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: npm install, build
        run: |
          yarn install
          yarn build
        env:
          CI: true

  deploy-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        env:
          CI: true
      - run: npm publish --access public
        name: publish on npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-GPR:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          registry-url: 'https://npm.pkg.github.com'
          scope: ${{ github.repository_owner }}
      - run: npm install
        env:
          CI: true
      - run: npx npe name @${{ github.event.repository.full_name }}
        name: change scope name
      - run: npm publish --access public --registry https://npm.pkg.github.com
        name: publish on GPR
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
